language: ruby

rvm:
  - 1.9.2
  - 1.9.3

before_install:
  - gem install bundler
#  - bash < <(curl -L https://raw.github.com/gist/1333785)

bundler_args: --without development assets

#before_script:
#  - "bundle exec rake db:setup db:migrate db:test:clone > /dev/null"

script: TRAVIS=1 bundle exec rspec spec

notifications:
  email: false

branches:
  only:
    - master