rvm:
  - 1.9.2
  - 1.9.3

bundler_args: --without development

before_install:
  #- bash < <(curl -L https://raw.github.com/gist/1333785)

before_script:
  - "sh -c 'rake db:migrate && rake db:seed'"

notifications:
  email: false