development:
  adapter: postgresql
  encoding: unicode
  database: portfolio_dev
  username: rails
  password: rails

test: &test
  adapter: postgresql
  encoding: unicode
  database: portfolio_test
  username: rails
  password: rails
