development:
  adapter: postgresql
  encoding: unicode
  database: portfolio_dev
  username: rails
  password: rails
test:
  adapter: postgresql
  encoding: unicode
  database: portfolio_test
  username: rails
  password: rails
production:
  adapter: postgresql
  encoding: unicode
  database: portfolio_prod
  username: rails
  password: rails